### ISSUE TITLE
Make sure we notify preact in disconnectedCallback

### ISSUE THREAD

**Issue by freeman** [skatejs/renderer-preact#5]
So that `componentWillUnmount` lifecycle methods are properly called on any child preact components.

See skatejs/skatejs#1244

**Comment by treshugart** [comment]
I wonder if it would be better to "unmount" the component, maybe replacing it with a div or something if you can't do that, so that it is compatible with whatever Preact does in the future on unmounting.

**Comment by treshugart** [comment]
This should also be done in https://github.com/skatejs/renderer-react.

**Comment by Hotell** [comment]
so this is a bug on our side or on the renderers side @treshugart  ?

**Comment by treshugart** [comment]
@Hotell it should be done within the renderers.
